name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  redploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Setup SSH and deploy
        run: |
          mkdir -p ~/.ssh

          ssh-keyscan -H 34.142.150.98 >> ~/.ssh/known_hosts

          echo "${{ secrets.SSH_PRIVATE_KEY_STAGING }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh prateekkumar@34.142.150.98 << 'EOF'
            cd ~/gcp-practice-repo
            git pull
            pnpm install
            pnpm build
            pm2 restart fe-server
            pm2 restart ws-server
            pm2 restart http-server
          EOF