name: Deploy to Staging
on:
  push:
    branches:
      - main

jobs:
  redploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_STAGING }}" &> ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/known_hosts 
          ssh -i ~/ssh_key prate@35.232.208.97 -t "
            export NVM_DIR=\"\$HOME/.nvm\"
            [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"

            cd gcp-practice-repo/ &&
            git pull &&
            corepack enable || true &&
            pnpm install &&
            pnpm build &&
            pm2 restart fe-server &&
            pm2 restart ws-server &&
            pm2 restart http-server
          "